### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by ClearlyElevated** [Jabrils-Discord-Server/ToS-Bot#9]
Hopefully you realize it’s against discord tos to download and copy data outside of discord unless it’s stored on a secure encrypted device. That would include making sure it’s by posted on GitHub. Adding a gitignore will fix this issue.

**Comment by Sv443** [comment]
What exactly do you mean?

**Comment by ClearlyElevated** [comment]
You need to really just make the repo private or delete it cuz u can still see commit history and access the data still

**Comment by Sv443** [comment]
Tell me how to do it without making the repo private, deleting it or losing the commit history and I'll do it
